name: laravel
recipe: laravel
config:
  php: '7.4'
  via: nginx
  webroot: public
services:
  database:
    type: mariadb
    creds:
      user: laravel
      password: laravel
      database: laravel
